AllCops:
  TargetRubyVersion: 2.3.0

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 125

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/IdentArray:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false